In [1]:
import numpy as np

In [2]:
ints = np.arange(24)

In [3]:
ints

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [5]:
arr2d = ints.reshape((6, 4))
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Slicing a NumPy Array

In [6]:
arr2d[0, :]

array([0, 1, 2, 3])

In [7]:
arr2d[:, 2]

array([ 2,  6, 10, 14, 18, 22])

In [8]:
arr2d[:, 2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

## Selecting from an Array

In [9]:
arr2d % 3 == 0

array([[ True, False, False,  True],
       [False, False,  True, False],
       [False,  True, False, False],
       [ True, False, False,  True],
       [False, False,  True, False],
       [False,  True, False, False]])

In [10]:
arr2d[arr2d % 3 == 0]

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [11]:
def is_prime(n):
    return n >= 2 and not any(n % i == 0 for i in range(2, n // 2 + 1))
is_prime = np.vectorize(is_prime, otypes=[np.bool])

In [12]:
is_prime(ints)

array([False, False,  True,  True, False,  True, False,  True, False,
       False, False,  True, False,  True, False, False, False,  True,
       False,  True, False, False, False,  True])

In [13]:
ints[is_prime(ints)]

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23])

In [14]:
bigger_ints = ints * 2
bigger_ints

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [15]:
bigger_ints[is_prime(ints)]

array([ 4,  6, 10, 14, 22, 26, 34, 38, 46])