In [36]:
import numpy as np

In [37]:
a = np.arange(6,14)

In [38]:
print(a)

[ 6  7  8  9 10 11 12 13]


In [39]:
print(a.shape)

(8,)


In [40]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [41]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [42]:
np.arange(0,20,1.5)

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ,
       16.5, 18. , 19.5])

In [43]:
np.linspace(0,1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [44]:
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [45]:
some_ints = np.array([[1,2], [3,4]], dtype=np.int64)
ident = np.identity(2, dtype=np.int32)
print(some_ints + ident)

[[2 2]
 [3 5]]


In [46]:
print(some_ints)

[[1 2]
 [3 4]]


In [47]:
print(ident)

[[1 0]
 [0 1]]


In [48]:
some_ints

array([[1, 2],
       [3, 4]])

In [49]:
some_ints.sum()

10

In [50]:
some_ints.sum(axis=1)

array([3, 7])

In [51]:
some_ints.sum(axis=0)

array([4, 6])

In [52]:
np.sum(some_ints, axis=0)

array([4, 6])

In [53]:
ints = np.arange(9)

In [54]:
ints

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
ints[0]

0

In [56]:
ints[-1]

8

In [57]:
ints = ints.reshape(3,3)

In [58]:
ints

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
ints[0,:]

array([0, 1, 2])

In [60]:
ints[:,2]

array([2, 5, 8])

In [32]:
ints[0,2]

2

In [33]:
ints > 6

array([[False, False, False],
       [False, False, False],
       [False,  True,  True]])

In [34]:
ints[ints>6]

array([7, 8])

In [35]:
ints.reshape(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
array = np.array([[1,2,3,4,5],[6,7,8,9,10]])
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

array([3, 8])